# tensorproduct with axes=0
#### Here we multiply each instance in x with each instance in y
### i.e. each instance in x is a scalor
##### should not be of the same size

In [18]:
w=np.array([[1, 3, 7],
            [2, 6, 8], 
            [3, 0, 8]
    
])
print (w.shape)
v= np.array([[3, 6, 4],
             [2, 8, 0],
    
])
print (v.shape)
d= np.tensordot(w, v, axes=0)
print (d)

(3, 3)
(2, 3)
[[[[ 3  6  4]
   [ 2  8  0]]

  [[ 9 18 12]
   [ 6 24  0]]

  [[21 42 28]
   [14 56  0]]]


 [[[ 6 12  8]
   [ 4 16  0]]

  [[18 36 24]
   [12 48  0]]

  [[24 48 32]
   [16 64  0]]]


 [[[ 9 18 12]
   [ 6 24  0]]

  [[ 0  0  0]
   [ 0  0  0]]

  [[24 48 32]
   [16 64  0]]]]


# tensorproduct with axes=1
#### Here we multiply each row in x with each column in y, then adds them
### i.e. each instance in x is a vector
##### the fist array should have no of rows as the second colmn's array

In [20]:
W=np.array([[1, 3, 7],
            [2, 6, 8], 
            [3, 0, 8]
    
])
print (W.shape)
V= np.array([[3, 6],
             [2, 8],
             [3, 9]
    
])
print (V.shape)
u= np.tensordot(W, V, axes=1)
print (u)

(3, 3)
(3, 2)
[[ 30  93]
 [ 42 132]
 [ 33  90]]


# tensordot with axes=2
#### Here we multiply array x with array y, then adds them
### i.e. each instance in x is a 2D tensor
##### the fist array should have the same shape as the second array

In [22]:
e=np.array([[1, 3, 7],
            [2, 6, 8], 
            [3, 0, 8]
    
])
print (e.shape)
f= np.array([[3, 6, 0],
             [2, 8, 8],
             [3, 9, 4]
    
])
print (f.shape)
G= np.tensordot(e, f, axes=2)
print (G)

(3, 3)
(3, 3)
178


## Difference between tensorproduct and tensordot

In [ ]:
#The tensor product is the product only of any 2 arrays together.
#The dot product combines two vectors into a scalar (a number). It is actually the inner product, by adding the summation after multiplication